SEED_RECIPE_NUTRITION = {
    "Espaguetis a la Carbonara": {"calories_per_serving": 735, "protein_g": 31, "carbs_g": 71, "fat_g": 36, "fiber_g": 3, "sugar_g": 4, "sodium_mg": 950, "meal_types": ["comida", "cena"]},
    "Macarrones con Tomate y Queso": {"calories_per_serving": 620, "protein_g": 24, "carbs_g": 78, "fat_g": 22, "fiber_g": 5, "sugar_g": 8, "sodium_mg": 740, "meal_types": ["comida", "cena"]},
    "Tortilla de Patatas": {"calories_per_serving": 410, "protein_g": 15, "carbs_g": 28, "fat_g": 26, "fiber_g": 3, "sugar_g": 3, "sodium_mg": 420, "meal_types": ["comida", "cena"]},
    "Arroz con Pollo": {"calories_per_serving": 560, "protein_g": 34, "carbs_g": 58, "fat_g": 20, "fiber_g": 3, "sugar_g": 5, "sodium_mg": 690, "meal_types": ["comida", "cena"]},
    "Pasta Boloñesa": {"calories_per_serving": 670, "protein_g": 35, "carbs_g": 76, "fat_g": 24, "fiber_g": 6, "sugar_g": 9, "sodium_mg": 780, "meal_types": ["comida", "cena"]},
    "Ensalada Mixta": {"calories_per_serving": 280, "protein_g": 16, "carbs_g": 10, "fat_g": 19, "fiber_g": 4, "sugar_g": 7, "sodium_mg": 520, "meal_types": ["comida", "cena"]},
    "Lasaña de Carne": {"calories_per_serving": 690, "protein_g": 37, "carbs_g": 58, "fat_g": 34, "fiber_g": 5, "sugar_g": 8, "sodium_mg": 920, "meal_types": ["comida", "cena"]},
    "Crema de Verduras": {"calories_per_serving": 215, "protein_g": 4, "carbs_g": 24, "fat_g": 11, "fiber_g": 5, "sugar_g": 7, "sodium_mg": 480, "meal_types": ["comida", "cena"]},
    "Pollo al Curry con Arroz": {"calories_per_serving": 590, "protein_g": 36, "carbs_g": 56, "fat_g": 24, "fiber_g": 4, "sugar_g": 6, "sodium_mg": 710, "meal_types": ["comida", "cena"]},
    "Fajitas de Pollo": {"calories_per_serving": 520, "protein_g": 33, "carbs_g": 42, "fat_g": 22, "fiber_g": 5, "sugar_g": 4, "sodium_mg": 840, "meal_types": ["comida", "cena"]},
    "Chili con Carne": {"calories_per_serving": 510, "protein_g": 32, "carbs_g": 39, "fat_g": 23, "fiber_g": 11, "sugar_g": 8, "sodium_mg": 880, "meal_types": ["comida", "cena"]},
    "Lentejas Estofadas": {"calories_per_serving": 470, "protein_g": 24, "carbs_g": 44, "fat_g": 20, "fiber_g": 13, "sugar_g": 6, "sodium_mg": 950, "meal_types": ["comida", "cena"]},
    "Garbanzos con Espinacas": {"calories_per_serving": 390, "protein_g": 18, "carbs_g": 36, "fat_g": 17, "fiber_g": 11, "sugar_g": 6, "sodium_mg": 650, "meal_types": ["comida", "cena"]},
    "Merluza al Horno con Patatas": {"calories_per_serving": 360, "protein_g": 35, "carbs_g": 22, "fat_g": 14, "fiber_g": 3, "sugar_g": 3, "sodium_mg": 420, "meal_types": ["comida", "cena"]},
    "Salmón con Verduras": {"calories_per_serving": 430, "protein_g": 32, "carbs_g": 16, "fat_g": 26, "fiber_g": 5, "sugar_g": 6, "sodium_mg": 390, "meal_types": ["comida", "cena"]},
    "Hamburguesas Caseras con Patatas": {"calories_per_serving": 760, "protein_g": 35, "carbs_g": 58, "fat_g": 42, "fiber_g": 5, "sugar_g": 7, "sodium_mg": 980, "meal_types": ["comida", "cena"]},
    "Albóndigas en Salsa": {"calories_per_serving": 540, "protein_g": 29, "carbs_g": 28, "fat_g": 34, "fiber_g": 4, "sugar_g": 8, "sodium_mg": 860, "meal_types": ["comida", "cena"]},
    "Pechugas de Pollo al Limón": {"calories_per_serving": 350, "protein_g": 38, "carbs_g": 6, "fat_g": 18, "fiber_g": 1, "sugar_g": 2, "sodium_mg": 480, "meal_types": ["comida", "cena"]},
    "Arroz Tres Delicias": {"calories_per_serving": 490, "protein_g": 18, "carbs_g": 58, "fat_g": 19, "fiber_g": 4, "sugar_g": 4, "sodium_mg": 790, "meal_types": ["comida", "cena"]},
    "Paella de Verduras": {"calories_per_serving": 430, "protein_g": 9, "carbs_g": 63, "fat_g": 13, "fiber_g": 6, "sugar_g": 7, "sodium_mg": 620, "meal_types": ["comida", "cena"]},
    "Risotto de Champiñones": {"calories_per_serving": 520, "protein_g": 14, "carbs_g": 58, "fat_g": 24, "fiber_g": 4, "sugar_g": 4, "sodium_mg": 710, "meal_types": ["comida", "cena"]},
    "Quiche de Espinacas y Queso": {"calories_per_serving": 480, "protein_g": 18, "carbs_g": 24, "fat_g": 34, "fiber_g": 3, "sugar_g": 4, "sodium_mg": 620, "meal_types": ["comida", "cena"]},
    "Pizza Casera de Jamón y Queso": {"calories_per_serving": 630, "protein_g": 28, "carbs_g": 67, "fat_g": 28, "fiber_g": 3, "sugar_g": 7, "sodium_mg": 1050, "meal_types": ["comida", "cena"]},
    "Burritos de Ternera": {"calories_per_serving": 610, "protein_g": 31, "carbs_g": 56, "fat_g": 28, "fiber_g": 10, "sugar_g": 5, "sodium_mg": 890, "meal_types": ["comida", "cena"]},
    "Cuscús con Verduras": {"calories_per_serving": 360, "protein_g": 12, "carbs_g": 53, "fat_g": 10, "fiber_g": 7, "sugar_g": 7, "sodium_mg": 420, "meal_types": ["comida", "cena"]},
    "Puré de Calabaza": {"calories_per_serving": 230, "protein_g": 5, "carbs_g": 29, "fat_g": 10, "fiber_g": 5, "sugar_g": 8, "sodium_mg": 430, "meal_types": ["comida", "cena"]},
    "Brochetas de Pollo y Verduras": {"calories_per_serving": 330, "protein_g": 34, "carbs_g": 8, "fat_g": 17, "fiber_g": 3, "sugar_g": 6, "sodium_mg": 520, "meal_types": ["comida", "cena"]},
    "Tacos de Pescado": {"calories_per_serving": 420, "protein_g": 27, "carbs_g": 34, "fat_g": 18, "fiber_g": 4, "sugar_g": 4, "sodium_mg": 650, "meal_types": ["comida", "cena"]},
    "Moussaka Rápida": {"calories_per_serving": 560, "protein_g": 28, "carbs_g": 26, "fat_g": 36, "fiber_g": 5, "sugar_g": 8, "sodium_mg": 760, "meal_types": ["comida", "cena"]},
    "Bacalao con Tomate": {"calories_per_serving": 340, "protein_g": 35, "carbs_g": 9, "fat_g": 17, "fiber_g": 3, "sugar_g": 7, "sodium_mg": 710, "meal_types": ["comida", "cena"]},
    "Ensalada César con Pollo": {"calories_per_serving": 450, "protein_g": 30, "carbs_g": 12, "fat_g": 30, "fiber_g": 3, "sugar_g": 4, "sodium_mg": 780, "meal_types": ["comida", "cena"]},
    "Tabulé": {"calories_per_serving": 260, "protein_g": 6, "carbs_g": 39, "fat_g": 9, "fiber_g": 4, "sugar_g": 5, "sodium_mg": 270, "meal_types": ["comida", "cena"]},
    "Pisto con Huevo": {"calories_per_serving": 310, "protein_g": 13, "carbs_g": 15, "fat_g": 21, "fiber_g": 5, "sugar_g": 10, "sodium_mg": 390, "meal_types": ["comida", "cena"]},
    "Berenjenas Rellenas": {"calories_per_serving": 460, "protein_g": 26, "carbs_g": 18, "fat_g": 30, "fiber_g": 7, "sugar_g": 9, "sodium_mg": 690, "meal_types": ["comida", "cena"]},
    "Croquetas de Jamón": {"calories_per_serving": 510, "protein_g": 18, "carbs_g": 38, "fat_g": 32, "fiber_g": 2, "sugar_g": 5, "sodium_mg": 820, "meal_types": ["comida", "cena"]},
    "Empanada de Atún": {"calories_per_serving": 420, "protein_g": 17, "carbs_g": 34, "fat_g": 24, "fiber_g": 2, "sugar_g": 5, "sodium_mg": 680, "meal_types": ["comida", "cena"]},
    "Sopa de Pollo con Fideos": {"calories_per_serving": 280, "protein_g": 18, "carbs_g": 24, "fat_g": 11, "fiber_g": 2, "sugar_g": 3, "sodium_mg": 720, "meal_types": ["comida", "cena"]},
    "Tortilla Francesa con Queso": {"calories_per_serving": 320, "protein_g": 22, "carbs_g": 3, "fat_g": 24, "fiber_g": 0, "sugar_g": 2, "sodium_mg": 430, "meal_types": ["desayuno", "cena"]},
    "Wrap de Pavo y Aguacate": {"calories_per_serving": 410, "protein_g": 22, "carbs_g": 28, "fat_g": 23, "fiber_g": 5, "sugar_g": 3, "sodium_mg": 640, "meal_types": ["desayuno", "comida", "cena"]},
    "Pollo Asado con Verduras": {"calories_per_serving": 520, "protein_g": 38, "carbs_g": 22, "fat_g": 30, "fiber_g": 4, "sugar_g": 6, "sodium_mg": 540, "meal_types": ["comida", "cena"]},
    "Pasta al Pesto": {"calories_per_serving": 580, "protein_g": 18, "carbs_g": 69, "fat_g": 25, "fiber_g": 4, "sugar_g": 4, "sodium_mg": 690, "meal_types": ["comida", "cena"]},
    "Ñoquis con Salsa de Quesos": {"calories_per_serving": 610, "protein_g": 19, "carbs_g": 66, "fat_g": 31, "fiber_g": 2, "sugar_g": 3, "sodium_mg": 740, "meal_types": ["comida", "cena"]},
    "Sandwich Club": {"calories_per_serving": 540, "protein_g": 33, "carbs_g": 36, "fat_g": 28, "fiber_g": 4, "sugar_g": 5, "sodium_mg": 890, "meal_types": ["desayuno", "comida", "cena"]},
    "Gazpacho Andaluz": {"calories_per_serving": 170, "protein_g": 3, "carbs_g": 14, "fat_g": 11, "fiber_g": 4, "sugar_g": 8, "sodium_mg": 380, "meal_types": ["comida", "cena"]},
    "Salmorejo Cordobés": {"calories_per_serving": 320, "protein_g": 8, "carbs_g": 23, "fat_g": 21, "fiber_g": 3, "sugar_g": 4, "sodium_mg": 600, "meal_types": ["comida", "cena"]},
    "Revuelto de Setas": {"calories_per_serving": 260, "protein_g": 18, "carbs_g": 5, "fat_g": 18, "fiber_g": 2, "sugar_g": 3, "sodium_mg": 360, "meal_types": ["desayuno", "cena"]},
    "Wok de Ternera y Verduras": {"calories_per_serving": 390, "protein_g": 31, "carbs_g": 15, "fat_g": 22, "fiber_g": 4, "sugar_g": 8, "sodium_mg": 760, "meal_types": ["comida", "cena"]},
    "Quesadillas de Jamón y Queso": {"calories_per_serving": 470, "protein_g": 24, "carbs_g": 36, "fat_g": 24, "fiber_g": 2, "sugar_g": 3, "sodium_mg": 760, "meal_types": ["desayuno", "comida", "cena"]},
}

LEGACY_RECIPE_NUTRITION = {
    "Desayuno": {"calories_per_serving": 420, "protein_g": 18, "carbs_g": 38, "fat_g": 20, "fiber_g": 5, "sugar_g": 7, "sodium_mg": 380, "meal_types": ["desayuno"]},
    "Filetes de pollo rebozados": {"calories_per_serving": 480, "protein_g": 24, "carbs_g": 42, "fat_g": 18, "fiber_g": 5, "sugar_g": 4, "sodium_mg": 620, "meal_types": ["comida", "cena"]},
}
